version: '3.7'

services:
    database:
        image: carottealpha/db:1.0
        networks:
          - app-network
        environment: 

          POSTGRES_DB: db
          POSTGRES_USER: usr
          POSTGRES_PASSWORD: pwd
        volumes:
          - db-data:/var/lib/postgresql/data
        
        

    backend:
        image: carottealpha/app:1.0
        networks:
          - app-network    
        environment:
          URL: jdbc:postgresql://database:5432/db
          USER: usr
          PWD: pwd      
        depends_on:
          - database
          - httpd
        container_name: api
        
        

    httpd:
        image: carottealpha/httpd:1.0
        ports:
          - "80:80"
        networks:
          - app-network

        
        

    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8080
        networks:
          - app-network
        depends_on:
          - database


networks:
  app-network:

volumes:
  db-data:
