version: '3.7'

services:
    database:
        image: carottealpha/tp-devops-simple-api-database
        networks:
          - app-network
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: usr
          POSTGRES_PASSWORD: pwd
        volumes:
          - db-data:/var/lib/postgresql/data
        container_name: pg
        #TODO

    backend:
        image: carottealpha/tp-devops-simple-api
        networks:
          - app-network    
        environment:
          URL: jdbc:postgresql://pg:5432/db
          USER: "usr"
          PWD: "pwd"      
        depends_on:
          - database
        container_name: api
        #TODO

    httpd:
        image: carottealpha/tp-devops-simple-api-httpd
        ports:
          - "80:80"
        networks:
          - app-network
        depends_on:
          - backend
        container_name: proxy
        #TODO

    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8090
        networks:
          - app-network
        depends_on:
          - database


networks:
  app-network:

volumes:
  db-data:
