version: '3.7'

services:
    backend:
        build:
          context: ./API
        
        networks:
          - app-network
          - db-network
        environment:
          URL: jdbc:postgresql://datase:5432/db
          USER: usr
          PWD: pwd

        depends_on:
          - database
        container_name: api


        #TODO

    database:
        build:
          context: ./Base
        networks:
          - db-network
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: usr
          POSTGRES_PASSWORD: pwd
        volumes:
          - db-data:/var/lib/postgresql/data

        #TODO

    httpd:
        build: ./Htpp
        ports:
          - "80:80"
        networks:
          - app-network     
        depends_on:
          - backend
        
        container_name: proxy
        #TODO

    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8080
        networks:
          - app-network
        depends_on:
          - database
    frontend:
        build: ./front
        networks:
            - app-network
        depends_on:
            - httpd
        environment:
            - VUE_APP_API_URL=http://localhost:80/api    

networks:
  app-network :
  db-network :

volumes:
  db-data:

