version: '3.7'

services:
    database:
        image: carottealpha/tp-devops-simple-api-database
        networks:
          - app-network
        environment: 
          POSTGRES_DB: db
          POSTGRES_USER: usr
          POSTGRES_PASSWORD: pwd
        volumes:
          - db-data:/var/lib/postgresql/data
        
        

    backend:
        image: carottealpha/tp-devops-simple-api
        networks:
          - app-network    
        environment:
          URL: jdbc:postgresql://database:5432/db
          USER: usr
          PWD: pwd      
        depends_on:
          - database
          - httpd
        
        

    httpd:
        image: carottealpha/tp-devops-simple-api-httpd
        ports:
          - "80:80"
        networks:
          - app-network

        
        

    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8080
        networks:
          - app-network
        depends_on:
          - database


networks:
  app-network:

volumes:
  db-data:
