---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: database
    image: carottealpha/tp-devops-simple-api-database:latest
    volumes:
      - /var/lib/postgresql/data
    env: 
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ usr_name }}"
      POSTGRES_PASSWORD: "{{ pwd_usr }}"
   
  vars:
    ansible_python_interpreter : /usr/bin/python3

    

  

