---
# tasks file for roles/app
- name: Run API
  docker_container:
    name: api
    image: carottealpha/tp-devops-simple-api:latest
    env:
      URL: "{{ URL }}"
      USER: "{{ usr_name }}"
      PWD: "{{ pwd_usr }}"
    recreate: yes
  vars:
    ansible_python_interpreter : /usr/bin/python3

  
