---
# tasks file for roles/app
- name: Run API
  docker_container:
    name: api
    image: mathismrg/tp1-backend:latest
    env:
      DB_URL: "{{ URL }}"
      DB_username: "{{ usr_name }}"
      DB_password: "{{ pwd_usr }}"
    networks:
      - name: networkAPI
    recreate: yes

  vars:
    ansible_python_interpreter : /usr/bin/python3

  
