---
# tasks file for roles/proxy
- name: Run HTTPD
  docker_container:
    name: httpd
    image: carottealpha/httpd:1.0
    ports: 
      - "80:80"
    networks:
      - name: networkAPI
  vars:
    ansible_python_interpreter : /usr/bin/python3
    
