---
# tasks file for roles/proxy
- name: Run HTTPD
  docker_container:
    name: httpd
    image: carottealpha/tp-devops-simple-api-httpd
    ports: 
      - "80:80"
    networks:
      - name: networkAPI
  vars:
    ansible_python_interpreter : /usr/bin/python3
    
