name: build-and-push-docker-image

on:
  # Trigger the workflow when a workflow run occurs on specified branches and when workflows named "test-backend" are completed
  workflow_run:
    branches:
      - main
    workflows: ["test-backend"]
    types: 
      - completed


jobs:
  build-and-push-docker-image:
    if: github.event.result.conclusion == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./TP1/API/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./TP1/Base/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./TP1/Htpp/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
