name: test-backend
on:
  # to begin you want to launch this job in main and develop
  push:
    # on donne les branches à tester (la develop existe pas encore)
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
   # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-22.04
    steps:
      # checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        # on utilise l'action setup java officiel
        uses: actions/setup-java@v3
        with:
          # on utilise le même jdk que le Dockerfile
          distribution: 'corretto'
          # on précise la même version que le Dockerfile
          java-version: '17'

      # finally build your app with the latest command
      - name: Build and test with Maven
        # on run maven clean verify dans le dossier du backend
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=sonardevopssebou_tp2 -Dsonar.organization=sonardevopssebou -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./TP1/API/simple-api-student-main/simple-api-student-main/pom.xml

       # run: mvn clean verify --file ./TP1/API/simple-api-student-main/simple-api-student-main/pom.xml

 